CREATE TABLE addresses (
	id INT NOT NULL PRIMARY KEY UNIQUE AUTO_INCREMENT,
	city VARCHAR(255) NOT NULL,
	country VARCHAR(255) NOT NULL,
	state VARCHAR(255) NOT NULL,
	street VARCHAR(255) NOT NULL,
	zip_code VARCHAR(255) NOT NULL
);

CREATE TABLE users (
	id INT NOT NULL PRIMARY KEY UNIQUE AUTO_INCREMENT,
	first_name VARCHAR(255) NOT NULL,
	last_name VARCHAR(255) NOT NULL,
	username VARCHAR(255) NOT NULL UNIQUE,
	email VARCHAR(255) NOT NULL UNIQUE,
	password VARCHAR(500) NOT NULL
);

CREATE TABLE roles (
	id INT NOT NULL PRIMARY KEY UNIQUE AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL UNIQUE
);