CREATE TABLE countries (
	id INT NOT NULL PRIMARY KEY UNIQUE,
	code VARCHAR(255) NOT NULL,
	name VARCHAR(255) NOT NULL,
	state VARCHAR(255) NOT NULL
);

CREATE TABLE states (
	id INT NOT NULL PRIMARY KEY UNIQUE,
	name VARCHAR(255) NOT NULL,
	country_id INT NOT NULL,
	CONSTRAINT fk_states_country_id FOREIGN KEY (country_id) REFERENCES countries (id),
);

CREATE TABLE roles (
	id INT NOT NULL PRIMARY KEY UNIQUE,
	name VARCHAR(255) NOT NULL UNIQUE
);